syntax enable
filetype on
filetype plugin on
filetype indent on
colorscheme torte
set cursorline
set cursorcolumn
let g:mapleader = " "

inoremap jk <Esc>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>
inoremap <C-l> <RIGHT>
nnoremap <silent> <C-s> :w<CR>
nnoremap <silent> <C-UP> :horizontal resize +5<CR>
nnoremap <silent> <C-DOWN> :horizontal resize -5<CR>
nnoremap <silent> <C-LEFT> :vertical resize +10<CR>
nnoremap <silent> <C-RIGHT> :vertical resize -10<CR>
nnoremap <silent> <S-c> :close<CR>
nnoremap <silent> <F2> :set relativenumber! number!<CR>
nnoremap <silent> no :set hlsearch!<CR>

if !isdirectory($HOME . '/.local/share/vim/view')
	call mkdir($HOME . '/.local/share/vim/view', 'p')
endif

if !isdirectory($HOME . '/.local/share/vim/backup')
	call mkdir($HOME . '/.local/share/vim/backup', 'p')
endif

set relativenumber
set showcmd
set splitright
set splitbelow
set laststatus=0
set ignorecase
set nohlsearch
set encoding=utf-8
set shiftwidth=4
set tabstop=4
set ruler
set nowrap
set history=1000
set backup
set backupdir=$HOME/.local/share/vim/backup//
set backupext=.bak
set textwidth=80
set autoindent
set smartindent
set fileformats=unix,dos,mac
set noswapfile
set foldlevel=3
set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
set clipboard+=unnamedplus
set virtualedit=
set fileencodings=ucs-bom,utf-8,gb18030,cp936,latin1"
set foldmethod=manual
set linebreak
set showmatch
set display=truncate
set guioptions+=b
set ambiwidth=double
set backspace=2
set foldclose=all
" set patchmode=.orig

" Return to last edit position when opening files (You want this!)
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" auto load view of folds
autocmd BufWritePre *  mkview
autocmd BufReadPost * loadview

set viewdir=$HOME/.local/share/vim/view
