[env]
TERM =  'xterm-256color'
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
  # background opacity
opacity = 1.0
dynamic_title = true
blur = true
resize_increments = true

[scrolling]
history = 10000

[font]
normal = { family = "VictorMono Nerd Font", style = "Bold" }
italic = { family = "VictorMono Nerd Font", style = "Italic" }
bold = { family = "VictorMono Nerd Font", style = "Bold" }
size = 16

[cursor]
# Block Underline | Beam
style = { shape = "Block", blinking = "Off" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
{ key = "PageUp", mods = "Shift", action = "IncreaseFontSize" },
{ key = "PageDown", mods = "Shift", action = "DecreaseFontSize" },
]
