import = [
    "/usr/share/alacritty/themes/pastel_dark.toml"
]

[env]
TERM =  'xterm-256color'
WINIT_X11_SCALE_FACTOR = "1.0"
WINIT_XIM_STYLE = "onscreen"  # let input method following cursor

[window]
# background opacity
opacity = 0.75
dynamic_title = true
blur = true
resize_increments = true
decorations = "None"
dynamic_padding = true
decorations_theme_variant = "None"

[scrolling]
history = 10000

[font]
normal = { family = "Comic Code", style = "Regular" }
italic = { family = "Comic Code", style = "Italic" }
bold = { family = "Comic Code", style = "Bold" }
size = 16
builtin_box_drawing = true 

[cursor]
# Block Underline | Beam
style = { shape = "Block", blinking = "off" }

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
{ key = "PageUp", mods = "Shift", action = "IncreaseFontSize" },
{ key = "PageDown", mods = "Shift", action = "DecreaseFontSize" },
]
